[package]
name = "blocktastic"
version = "0.1.0"
authors = ["Kartikaya Gupta"]
edition = "2021"
license = "0BSD"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"
hmac-sha256 = "1.1.4"
